version: '3'

volumes:
  mysql_volume:

networks:
  go_network:

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart : always
    networks:
      - go_network
    ports:
      - 3306:3306
    volumes:
    - mysql_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=devcode