version: '3'

volumes:
  api:
  mysql_volume:

networks:
  go_network:

services:
  app:
    container_name: devcode
    build: .
    ports: 
      - 3030:3030 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - mysql          
    networks:
      - go_network
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart : always
    networks:
      - go_network
    ports:
      - 3306:3306
    volumes:
    - mysql_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DBNAME}
      - MYSQL_PORT=${MYSQL_PORT}