version: '3'

volumes:
  api:
  mysql_volume:

networks:
  go_network:
    driver: bridge

services:
  app:
    container_name: devcode
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3030:3030 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - devcode-mysql
    links:
      - devcode-mysql
    environment:
      - MODE=DEV
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DBNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - go_network
  devcode-mysql:
    container_name: devcode_db_mysql
    image: mysql:8.0
    restart : always
    networks:
      - go_network
    ports:
      - 3306:3306
    volumes:
    - mysql_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DBNAME}